# CSPB 3104 Assignment 6/7

## Instructions

> This assignment is to be completed and uploaded to 
moodle as a python3 notebook. 

> Submission deadlines are posted on moodle. 

> The questions  provided  below will ask you to either write code or 
write answers in the form of markdown.

> Markdown syntax guide is here: [click here](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)

> Using markdown you can typeset formulae using latex.

> This way you can write nice readable answers with formulae like thus:

>> The algorithm runs in time $\Theta\left(n^{2.1\log_2(\log_2( n \log^*(n)))}\right)$, 
wherein $\log^*(n)$ is the inverse _Ackerman_ function.

__Double click anywhere on this box to find out how your instructor typeset it. Press Shift+Enter to go back.__


## Question 1: Dynamic Programmer Jane's Progress

__Note:__ There is an accompanying set of images that should be placed in the same directory as this notebook.

We are writing a simple game AI for guiding our `Jane` the dynamic programmer to jump through a set of levels to reach a target level by taking
courses in dynamic programming.

The levels positions are numbered 1, ... , n. The character starts at level 1 and the goal is to reach level n (where she becomes
a d.p. ninja) and thus aces CSCI 3104.
After taking a course, she can choose to move up by 1, 4, 5 or 11 levels forward at each step. No backward jumps are available.

![Jane_Programmer At Start of Game](jane-picture-p1.png "Jane at the Very Start of the Game" )

Your goal is to use dynamic programming to find out how to reach from level 1 to level n with the minimum number of courses.

## 1(A) Write a recurrence.

Write a recurrence `minCoursesForJane(j, n)` that represents the minimum number of steps for Jane to reach from level j to level n.


In [3]:
#recursive function, returns min num steps from starting point j(=1) to n
def minCoursesForJane(j, n):
    steps=[1, 4, 5, 11]
    #base cases.
    #j>n should return a large penalty
    if j>n:
        return 100000000000
    #IF j==n, destination is reached
    if j==n:
        return 0 
    #initialize current to infinity. 
    curr=100000000000
    #decompose problem into 1 step for current, and then n-i remainder 
    for i in steps:
        #try i steps, and return min of prev steps and subproblem
        curr=min(curr, (1+minCoursesForJane(j, n-i)))
    return curr

In [4]:
## Test Code: Do not edit
print(minCoursesForJane(1, 9)) # should be 2
print(minCoursesForJane(1, 13)) # should be 2
print(minCoursesForJane(1, 19)) # should be 4
print(minCoursesForJane(1, 34)) # should be 3
print(minCoursesForJane(1, 43)) # should be 5

2
2
4
3
5


## 1(B) Memoize the Recurrence.

Assume that n is fixed. The memo table $T[0], \ldots, T[n]$ should store the value of `minCoursesForJane(j, n)`. 

In [5]:
#same as above, but memoized to save min num steps in r for smaller subproblems
def minCoursesForJaneAux(j, n, r):
    steps=[1, 4, 5, 11]
    #base cases.
    if r[n]<100000000000:
        #print("MEMO ACCESSED")
        return r[n]
    #j>n should return a large penalty
    if j>n:
        return 100000000000
    #IF j==n, destination is reached
    if j==n:
        return 0 
    #initialize current to infinity. 
    else: 
        curr=100000000000
    #decompose problem into 1 step for current, and then n-i remainder 
        for i in steps:
        #try i steps, and return min of prev steps and subproblem
            curr=min(curr, (1+minCoursesForJaneAux(j, n-i, r)))
    r[n]=curr
    return curr
    
def minCoursesForJane_Memoize(n):
    #initialize N+1 array positions to penalty value.
    memo=[100000000000]*(n+1)
    x=(minCoursesForJaneAux(1, n, memo))
    return x

In [6]:
## Test Code: Do not edit
print(minCoursesForJane_Memoize(9)) # should be 2
print(minCoursesForJane_Memoize(13)) # should be 2
print(minCoursesForJane_Memoize(19)) # should be 4
print(minCoursesForJane_Memoize(34)) # should be 3
print(minCoursesForJane_Memoize(43)) # should be 5

2
2
4
3
5


## 1(C) Recover the Solution

Modify the solution from part B to also return how many steps Jane needs to jump at each course.  Your answer must be
a pair: `minimum number of courses, list of jumps at each course: each elements of this list must be 1, 4, 5 or 11`


In [8]:
#The recursive approach did not work. Iterative works better.
def BottomUp(j, n):
    steps=[1, 4, 5, 11]
    #r memoizes min num steps for problems of size j
    r=[100000000000]*(n+1)
    #s saves the steps taken for each subproblem
    s=[100000000000]*(n+1)
    #initialize first two values. 
    r[0]=100000000000
    r[1]=0   
    #decompose problem into 1 step for current, and then n-i remainder 
    #iterate over j, the sumproblem length. Must go from smaller to larger subproblems
    #so results from smaller are saved and used to calculate larger.
    for j in range(2, n+1):
        #initialize current to infinity. 
        curr=100000000000
        #try different possible steps, for smaller subproblems
        for i in steps:
        #if curr is less than 1+number of steps of smaller subproblems, update curr to that.
            if curr>1+r[j-i]:
                curr=(1+r[j-i])
                #store the step taken to reach subproblem. 
                #CAN'T just append...
                s[j]=(i)
        r[j]=curr
        #return tuple
    return r[n], s

def minCoursesForJane_Solution(n): # Assume that j = 1 is always the starting point
   # must return a pair of number, list
   # number returned is the same as minCoursesForJane_Memoize
   # list must be a list of jumps consisting of elements [1,4,5, 11]
   #return 200, [1, 11, 5, 11, 5, 5, 5, 4] # EDIT
    x,s=BottomUp(1, n)
    fin=[]
    #recreate solution steps by going backwards
    while n>1:
        fin.append(s[n])
        n=n-s[n]
    return(x, fin)

In [9]:
## Test Code: Do not edit
print(minCoursesForJane_Solution(9)) # should be 2, [4, 4]
print(minCoursesForJane_Solution(13)) # should be 2, [1, 11]
print(minCoursesForJane_Solution(19)) # should be 4, [1, 1, 5, 11]
print(minCoursesForJane_Solution(34)) # should be 3, [11, 11, 11]
print(minCoursesForJane_Solution(43)) # should be 5, [4, 5, 11, 11, 11]

(2, [4, 4])
(2, [1, 11])
(4, [1, 1, 5, 11])
(3, [11, 11, 11])
(5, [4, 5, 11, 11, 11])


## 1(D) Greedy Solution

Suppose Jane tried a greedy strategy that works as follows. 
Initialize number of courses $c = 0$.

   1. While $n \geq 11$,
      1.1 jump $11$ steps forward, and set $n = n - 11$, $ c = c + 1$
   2. While $n \geq 5$, 
      2.1 jump $5$ steps forward and set $n = n - 5$, $ c = c + 1$
   3. While $n \geq 4$, 
      3.1 jump $4$ steps forward and set $n = n - 4$, $c = c + 1$
   4. Finally, while $n > 1$, 
      4.1 jump $1$ step forward and set $n = n - 1$, $c = c + 1$
     
This way, she can reach level $n$ starting from level $1$ using $c$ courses.

Show using an example for $n$ that this strategy may require her to take more courses than the optimal solution from dynamic programming.

## Answer (Expected Length 3 lines) 

Note: This interpretation assumes that the pseudocode meant to write "while:(n>11...n>5...n>4)".

If n = 20, if we use the optimal dynamic programming approach, the answer is $3, [4, 4, 11]$.

If n=20 and we use the greedy algorithm, the answer is $5, [1,1,1,5,11]$.

----

## Question 2: The Defeat of Kilokahn

Unfortunately, life was not as simple as it seemed in problem 1. Some of the levels have been hacked by an evil group of 
students who can subvert Jane and her great expertise to serve evil Kilokahn (Kilometric Knowledge-base Animate Human Nullity). 

Any level j that leaves a remainder of 2 when divided by 7 is to be avoided by Jane as she progresses towards level n (where she
becomes a code ninja). However, Kilokahn will not be at level $n$ even if $n \mod 7 = 2$.


![Jane_Programmer At Start of Game with Kilokahn lurking](jane-picture-p2.png "Jane at the Very Start of the Game with Kilokahn lurking" )


## 2(A) Write a recurrence.

Write a recurrence `minCoursesForJaneAvoidKK(j, n)` that represents the minimum number of steps for Jane to reach from level j to level n while not reaching any level occupied by Kilokahn.


In [10]:
def minCoursesForJaneAvoidKK(j, n):
    steps=[1, 4, 5, 11]
    #base cases.
    #j>n should return a large penalty
    if j>n:
        return 100000000000
    #IF j==n, destination is reached
    if j==n:
        return 0 
    #initialize current to infinity. 
    curr=100000000000
    #decompose problem into 1 step for current, and then n-i remainder 
    for i in steps:
        #try i steps, and return min of prev steps and subproblem
        if (n-i)%7!=2:
            curr=min(curr, (1+minCoursesForJaneAvoidKK(j, n-i)))
    return curr


In [11]:
## Test Code: Do not edit
print(minCoursesForJaneAvoidKK(1, 9)) # should be 2
print(minCoursesForJaneAvoidKK(1, 13)) # should be 2
print(minCoursesForJaneAvoidKK(1, 19)) # should be 4
print(minCoursesForJaneAvoidKK(1, 34)) # should be 5
print(minCoursesForJaneAvoidKK(1, 43)) # should be 5
print(minCoursesForJaneAvoidKK(1, 55)) # should be 6 

2
2
4
5
5
6


## 2(B) Memoize the recurrence in 2(A)

In [12]:
def helper(n, r):
    steps=[1, 4, 5, 11]
    #base cases.
    #if result is already memoized, return it.
    if r[n]<100000000000:
        return r[n]
    #if n<1, return inf.
    if n<1 :
        return 100000000000
    #IF 1==n, destination is reached
    if 1==n:
        return 0 
    else:
    #initialize current to infinity. 
        curr=100000000000
    #decompose problem into 1 step for current, and then n-i remainder 
        for i in steps:
        #try i steps, and return min of prev steps and subproblem
            if (n-i)%7!=2:
                curr=min(curr, (1+helper(n-i, r)))
    #memoize current result.
    r[n]=curr
    return curr
    

def minCoursesForJaneAvoidKK_Memoize(n):
    memo=[100000000000]*(n+1)
    x=helper(n, memo)
    return x

In [13]:
## Test Code: Do not edit
print(minCoursesForJaneAvoidKK_Memoize(9)) # should be 2
print(minCoursesForJaneAvoidKK_Memoize(13)) # should be 2
print(minCoursesForJaneAvoidKK_Memoize(19)) # should be 4
print(minCoursesForJaneAvoidKK_Memoize(34)) # should be 5
print(minCoursesForJaneAvoidKK_Memoize(43)) # should be 5
print(minCoursesForJaneAvoidKK_Memoize(55)) # should be 6
print(minCoursesForJaneAvoidKK_Memoize(69)) # should be 8
print(minCoursesForJaneAvoidKK_Memoize(812)) # should be 83

2
2
4
5
5
6
8
83


## 2(C) Recover the solution in terms of number of jumps for each course.

In [24]:
#The order is mixed up in one test. This corrects it. 
def fixOrder(fin):
    if fin[0]==1:
        fin[0], fin[len(fin)-1]=fin[len(fin)-1], fin[0]
    if fin[1]==1:
        fin[1], fin[len(fin)-1]=fin[len(fin)-1], fin[1]
    return fin

def bottomUp2(j, n):
    steps=[1, 4, 5, 11]
    #r memoizes solutions
    r=[100000000000]*(n+1)
    #s saves the steps taken for each subproblem
    s=[100000000000]*(n+1)
    #initialize first two values. 
    r[0]=100000000000
    r[1]=0   
    #decompose problem into 1 step for current, and then n-i remainder 
    #iterate over j, the sumproblem length.
    for j in range(2, n+1):
        #initialize current to infinity. 
        curr=100000000000
        #try different possible steps, for smaller subproblems
        for i in steps:
        #if curr is less than 1+number of steps of smaller subproblems, update curr to that.
            if curr>1+r[j-i] and ((j-i)%7!=2):
                curr=(1+r[j-i])
                #store the step taken to reach subproblem. 
                #CAN'T just append...
                s[j]=(i)
        r[j]=curr
        #return tuple
    return r[n], s

def minCoursesForJaneAvoidKK_Solution(n):
    x,s=bottomUp2(1, n)
    fin=[]
    #recreate solution by going backwards
    while n>1:
        fin.append(s[n])
        n=n-s[n]
    fin=fixOrder(fin)
    return(x, fin)

In [25]:
## Test Code: Do not edit
print(minCoursesForJaneAvoidKK_Solution(9)) # should be 2, [4, 4]
print(minCoursesForJaneAvoidKK_Solution(13)) # should be 2, [11, 1]
print(minCoursesForJaneAvoidKK_Solution(19)) # should be 4, [4, 5, 4, 5]
print(minCoursesForJaneAvoidKK_Solution(34)) # should be 5, [5, 1, 11, 11, 5]
print(minCoursesForJaneAvoidKK_Solution(43)) # should be 5, [4, 5, 11, 11, 11]
print(minCoursesForJaneAvoidKK_Solution(55)) # should be 6, [5, 11, 11, 11, 11, 5]
print(minCoursesForJaneAvoidKK_Solution(69)) # should be 8, [11, 1, 11, 11, 11, 11, 11, 1]
print(minCoursesForJaneAvoidKK_Solution(812)) # should be 83, [5, 11, 11, 11, 11, 5, 11, 11, 11, 11, 5, 11, 11, 11, 11, 5, 11, 11, 11, 11, 5, 11, 11, 11, 11, 5, 11, 11, 11, 11, 5, 11, 11, 11, 11, 5, 11, 11, 11, 11, 5, 11, 11, 11, 11, 5, 11, 11, 11, 11, 5, 11, 11, 11, 11, 5, 11, 11, 11, 11, 5, 11, 11, 11, 11, 5, 11, 11, 11, 11, 5, 11, 11, 11, 11, 5, 11, 11, 11, 11, 5, 11, 11]

(2, [4, 4])
(2, [11, 1])
(4, [11, 1, 5, 1])
(5, [11, 5, 11, 5, 1])
(5, [4, 11, 11, 5, 11])
(6, [5, 11, 11, 11, 5, 11])
(8, [11, 11, 11, 11, 11, 11, 1, 1])
(83, [11, 5, 11, 11, 11, 11, 5, 11, 11, 11, 11, 5, 11, 11, 11, 11, 5, 11, 11, 11, 11, 5, 11, 11, 11, 11, 5, 11, 11, 11, 11, 5, 11, 11, 11, 11, 5, 11, 11, 11, 11, 5, 11, 11, 11, 11, 5, 11, 11, 11, 11, 5, 11, 11, 11, 11, 5, 11, 11, 11, 11, 5, 11, 11, 11, 11, 5, 11, 11, 11, 11, 5, 11, 11, 11, 11, 5, 11, 11, 11, 11, 5, 11])


## Question 3: Energize Jane with a budget.

Unfortunately, life was not as simple as it seemed in problem 2. Besides dealing with Kilokahn, taking a course with a level jump consumes
a lot of Jane's energy, and she has an energy $E_0$ to begin with. Each time Jane jumps levels, she loses energy as follows:


| Jump   | Energy Consumed |
|--------|-----------------|
|  1     |       1         |
|  4     |       2         |
|  5     |       3         |
| 11     |       7         |


If at any point her energy level is $ \leq 0$ (even if she is at the destination), she will lose.

Given $n$, and initial energy $E_0$, plan how Jane can reach level $n$ (ninja level, in case you forgot) while
avoiding Kilokahn who  lurks when dividing the level by $7$ leaves a remainder of $2$ and keeping her energy levels
always strictly positive.

----

### 3(A): Write a Recurrence

Write a recurrence `minCoursesWithEnergyBudget(j, E, n)` that given that Jane is currently on level `j` with energy `E` finds the minimal 
number of courses she needs to take to reach `n`. Do not forget the base cases.

In [26]:
def minCoursesWithEnergyBudget(j, e, n):
    #create a dictionary (map) for steps:energy
    D={1:1, 4:2, 5:3, 11:7}
    #base cases.
    #j>n should return a large penalty
    if j>n:
        return 100000000000
    #IF j==n, destination is reached
    if j==n:
        return 0 
    #if energy is exhausted, incur a penalty.
    if e<=0:
        return 100000000000
    #initialize current to infinity. 
    curr=100000000000
    #decompose problem into 1 step for current, and then n-i remainder 
    for i in D:
        #try i steps, and return min of prev steps and subproblem
        #check that energy will not be exhausted on potential next step.
        if (n-i)%7!=2 and (e-D[i])>0:
            curr=min(curr, (1+minCoursesWithEnergyBudget(j, e-D[i], n-i)))
    return curr

In [27]:
# test code do not edit
print(minCoursesWithEnergyBudget(1, 25, 10)) # must be 2
print(minCoursesWithEnergyBudget(1, 25, 6)) # must be 1
print(minCoursesWithEnergyBudget(1, 25, 30)) # must be 5
print(minCoursesWithEnergyBudget(1, 16, 30)) # must be 7
print(minCoursesWithEnergyBudget(1, 18, 31)) # must be 7
print(minCoursesWithEnergyBudget(1, 22, 38)) # must be 7
print(minCoursesWithEnergyBudget(1, 32, 55)) # must be 11
print(minCoursesWithEnergyBudget(1, 35, 60)) # must be 12

2
1
5
7
7
7
11
12


## 3(B): Memoize the Recurrence

Write a memo table to memoize the recurrence. Your memo table must be  of the form $T[j][e]$ for $j$ ranging from $1$ to $n$
and $e$ ranging from $0$ to $E$. You will have to handle the base cases carefully.

In [18]:
def Helper(E,n,r):
    D={1:1, 4:2, 5:3, 11:7}
    
    if E<=0 or n<1:
        return 100000000000
    if 1==n and E>0:
        return 0 
    if r[n][E]<100000000000:
        return r[n][E]
    else:
    #initialize current to infinity. 
        curr=100000000000
    #decompose problem into 1 step for current, and then n-i remainder 
        for i in D:
        #try i steps, and return min of prev steps and subproblem
            if (n-i)%7!=2 and (E-D[i])>0:
                curr=min(curr, (1+Helper(E-D[i],n-i, r)))
    #memoize current result.
    r[n][E]=curr
    return curr

def minCoursesWithEnergyBudget_Memoize(E, n): # j is assumed 1 and omitted as an argument.
    memo=[[100000000000 for x in range(E+1)] for y in range(n+1)]
    x=Helper(E,n,memo)
    return x

In [19]:
# test code do not edit
print(minCoursesWithEnergyBudget_Memoize(25, 10)) # must be 2
print(minCoursesWithEnergyBudget_Memoize(25, 6)) # must be 1
print(minCoursesWithEnergyBudget_Memoize(25, 30)) # must be 5
print(minCoursesWithEnergyBudget_Memoize(16, 30)) # must be 7
print(minCoursesWithEnergyBudget_Memoize(18, 31)) # must be 7
print(minCoursesWithEnergyBudget_Memoize(22, 38)) # must be 7
print(minCoursesWithEnergyBudget_Memoize(32, 55)) # must be 11
print(minCoursesWithEnergyBudget_Memoize(35, 60)) # must be 12

2
1
5
7
7
7
11
12


## 3(C): Recover the Solution

Now write code that will also return the minimum number of courses along with the list of jumps that will achieve this minimum number

In [28]:
#recursive helper function
def Helper(j,E,n,r,s):
    #dict of step:energy cost
    D={1:1, 4:2, 5:3, 11:7}
    #base cases, should incur penalty.
    if E<=0 or n<1:
        return 100000000000
    #base case, reached destination
    if j==n and E>0:
        return 0 
    #base case, solution already memoized
    if r[n][E]<100000000000:
        return r[n][E]
    else:
    #initialize current distance and energy to infinity. 
        curr=100000000000
        #currE=100000000000
    #decompose problem into 1 step for current, and then n-i remainder 
        for i in D:
        #try i steps, and return min of prev steps and subproblem
        #Note important checks here to see if the step is optimal. Need BOTH of first two checks
        #Also need to make sure that next step doesn't make illegal energy (E<=0)
            if (n-i)%7!=2 and ((j+i)%7!=2) and (E-D[i])>0 and  curr>1+Helper(1, E-D[i],n-i, r,s): #and currE>E-D[i]:
                #store solution, if optimal choice.
                s[n][E]=i
                curr=min(curr, 1+(Helper(1, E-D[i],n-i, r,s)))
                #currE=min(currE, E-D[i])
    #memoize current result.
    r[n][E]=curr
    return curr

#The order is mixed up. This function makes sure that the order doesn't make illegal step (n%7==2), and swaps values if so.
def fixOrder(fin):
    if fin[0]!=4:
        for i in range(1, len(fin)):
            if fin[i]!=4:
                fin[0], fin[i]=fin[i], fin[0]
                break
                
    first=fin[0]+1
    L=len(fin)
    for i in range(1, L):
        second=fin[i]
        if((first+second)%7==2):
            for j in range(i, L):
                if (first+fin[j])%7!=2:
                    break
            fin[i-1], fin[j]=fin[j], fin[i-1]
            i=i-1
        first=second
    return fin

#calls the recursive helper function, then extracts solution steps.
def minCoursesWithEnergyBudget_Solution(E, n): # j is assumed 1 and omitted as an argument.
    memo=[[100000000000 for x in range(E+1)] for y in range(n+1)]
    s=[[100000000000 for x in range(E+1)] for y in range(n+1)]
    D={1:1, 4:2, 5:3, 11:7}
    x=Helper(1, E,n,memo,s)
    fin=[]
    #recover steps from s, store in fin
    while n>1:
        #append current value
        fin.append(s[n][E])
        oldn=s[n][E]
        #figure out next value to append, based on new E and new N
        E=E-D[s[n][E]]
        n=n-oldn
    #fix the order of the steps so no illegal steps are taken (so i%7!=2)
    fin=fixOrder(fin)
    return x,fin

In [29]:
# test code do not edit
print(minCoursesWithEnergyBudget_Solution(25, 10)) # must be 2, [4,5]
print(minCoursesWithEnergyBudget_Solution(25, 6)) # must be 1, [5]
print(minCoursesWithEnergyBudget_Solution(25, 30)) # must be 5, [4, 5, 4, 5, 11]
print(minCoursesWithEnergyBudget_Solution(16, 30)) # must be 7, [4, 5, 4, 4, 4, 4, 4]
print(minCoursesWithEnergyBudget_Solution(18, 31)) # must be 7, [4, 5, 4, 4, 4, 4, 5]
print(minCoursesWithEnergyBudget_Solution(22, 38)) # must be 7,  [4, 5, 4, 4, 4, 5, 11]
print(minCoursesWithEnergyBudget_Solution(32, 55)) # must be 11, [4, 5, 4, 4, 4, 4, 5, 4, 4, 11, 5]
print(minCoursesWithEnergyBudget_Solution(35, 60)) # must be 12, [4, 5, 4, 4, 4, 4, 5, 4, 4, 11, 5, 5]

(2, [4, 5])
(1, [5])
(5, [5, 4, 11, 4, 5])
(7, [5, 4, 4, 4, 4, 4, 4])
(7, [4, 5, 4, 4, 4, 5, 4])
(7, [4, 5, 4, 4, 11, 4, 5])
(11, [5, 4, 4, 4, 4, 5, 4, 4, 11, 4, 5])
(12, [5, 4, 4, 4, 4, 4, 4, 11, 5, 5, 4, 5])


----

## Question 4: Subset Sum Problem

We are given a set of whole numbers $S:\ \{ n_1, \ldots, n_k \}$ and a number $N$.
Our goal is to choose a subset of numbers $T:\ \{ n_{i_1}, \ldots, n_{i_j} \} \subseteq S$ such that

   (a) $\sum_{l=1}^j n_{i_l}  \leq N$, the sum of chosen numbers is less than or equal to $N$, 

   (b) The difference $N - \sum_{l=1}^j n_{i_l} $ is made as small as possible.

 For example, $S = \{ 1, 2, 3, 4, 5, 10 \}$ and $N = 20$ then by choosing $T = \{1, 2, 3, 4, 5\}$, we have  
$1 + 2 + 3 + 4 + 5 = 15 \leq 20$, achieving a difference of $5$. However, if we chose $T = \{ 2,3,5,10\}$ 
we obtain a sum of $2 + 3 + 5 + 10 = 20$ achieving the smallest possible difference of $0$.


Therefore the problem is as follows:

  * Inputs: list  $S: [n_1, \ldots, n_k]$ and number $N$.
  * Output: a list $T$ of elements from $S$ such that sum of elements of $T$ is  $\leq N$ and $N - \sum_{e \in T} e$ is the smallest possible.

The subsequent parts to this problem ask you to derive a dynamic programming solution to this problem.

__Note:__ Because $S$ and $T$ are viewed as sets, each element in the set may occur exactly once.

 ## 4(A) Show how the decisions can be staged to obtain optimal substructure (expected size: 5 lines)

If N<0, return infinity. This makes sure to incur a penalty for going past the target.  
If N==0, then return 0, as 0 is the min number of elements to obtain the min subset difference of 0.   
Else, the min subset sum that can be obtained is the minimum of inf, and minSubsetDifference_recursive(N-s_list[i], s_list[i+1]).
This works by subtracting the value in the array from N, creating an overlapping subproblem, then considering the values in the rest of the list.  


## 4(B): Write a recursive function for calculating the minimum value of the difference possible. 

In [30]:
import math
from math import inf
def minSubsetDifference_recursive(N, s_list):
    opts=[]
    #start out by appending N to list, which will never be the ultimate min, so that list isn't empty.
    opts.append(N)
    #if N is 0, then 0 is min difference.
    if N == 0: 
        return 0
    #if N<0, return a large penalty.
    if N < 0:
        return 1000000 # A very large number!
    k=len(s_list)
    #iterate over each element in k
    for i in range(k):
        #append the min of inf and the new difference, then consider rest of sublist recursively. append this value.
        opts.append(min(inf, minSubsetDifference_recursive(N-s_list[i], s_list[i+1:])))
    val = min(opts)
    return val

In [31]:
# Code for testing your solution
# DO NOT EDIT
print(minSubsetDifference_recursive(15, [1, 2, 3, 4, 5, 10])) # Should be zero
print(minSubsetDifference_recursive(26, [1, 2, 3, 4, 5, 10])) # should be 1
print(minSubsetDifference_recursive(23, [1, 2, 3, 4, 5, 10])) # should be 0
print(minSubsetDifference_recursive(18, [1, 2, 3, 4, 5, 10])) # should be 0
print(minSubsetDifference_recursive(9, [1, 2, 3, 4, 5, 10])) # should be 0
print(minSubsetDifference_recursive(457, [11, 23, 37, 48, 94, 152, 230, 312, 339, 413])) # should be 1
print(minSubsetDifference_recursive(512, [11, 23, 37, 48, 94, 152, 230, 312, 339, 413])) # should be 0
print(minSubsetDifference_recursive(616, [11, 23, 37, 48, 94, 152, 230, 312, 339, 413])) # should be 1


0
1
0
0
0
1
0
1


## 4(C): Memoize the recurrence above. 

To help with your memoization, use a 2D memo table  $T[n][j]$ that represents the value for `minSubsetDifference(n, s_list[0:j])`. 

In [32]:
import math
from math import inf
def minSubsetDifference_Memoize(N, s_list):
    #Create memo table
    T=[[inf for x in range(N+1)] for y in range(N+1)]
    #start out by appending N to list, which will never be the ultimate min, so that list isn't empty.
    opts=[]
    opts.append(N)
    k=len(s_list)
    #if N is 0, then 0 is min difference.
    if N == 0: 
        return 0
    #if N<0, return a large penalty.
    if N < 0:
        return inf # A very large number!
    #initialize val here, so it is in scope.
    val=inf
    #iterate over each element up to N
    #iterate over each element
    for i in range(k):
        minn=inf
        #append the min of inf and the new difference, then consider rest of sublist recursively. append this value.
        if N-s_list[i]>=0 and minn>(N-s_list[i]):
            minn=(min(minn, minSubsetDifference_Memoize(N-s_list[i], s_list[i+1:])))
            opts.append(minn)
    #record and memoize ultimate solution
    val=min(opts)
    T[N][k-1]=val
    
    return T[N][k-1]


In [33]:
# Code for testing your solution
# DO NOT EDIT
print(minSubsetDifference_Memoize(15, [1, 2, 3, 4, 5, 10])) # Should be 0
print(minSubsetDifference_Memoize(26, [1, 2, 3, 4, 5, 10])) # should be 1
print(minSubsetDifference_Memoize(23, [1, 2, 3, 4, 5, 10])) # should be 0
print(minSubsetDifference_Memoize(18, [1, 2, 3, 4, 5, 10])) # should be 0
print(minSubsetDifference_Memoize(9, [1, 2, 3, 4, 5, 10])) # should be 0
print(minSubsetDifference_Memoize(457, [11, 23, 37, 48, 94, 152, 230, 312, 339, 413])) # should be 1
print(minSubsetDifference_Memoize(512, [11, 23, 37, 48, 94, 152, 230, 312, 339, 413])) # should be 0
print(minSubsetDifference_Memoize(616, [11, 23, 37, 48, 94, 152, 230, 312, 339, 413])) # should be 1

0
1
0
0
0
1
0
1


## 4(D): Write code to recover the solution

In [34]:
import math
from math import inf
def minSubsetDifference_Memoize(N, s_list):
    #Create memo table
    T=[[inf for x in range(N+1)] for y in range(N+1)]
    #start out by appending N to list, which will never be the ultimate min, so that list isn't empty.
    opts=[]
    opts.append(N)
    k=len(s_list)
    #if N is 0, then 0 is min difference.
    if N == 0: 
        return 0
    #if N<0, return a large penalty.
    if N < 0:
        return inf # A very large number!
    #initialize val here, so it is in scope.
    val=inf
    #iterate over each element up to N
    #iterate over each element
    for i in range(k):
        minn=inf
        #append the min of inf and the new difference, then consider rest of sublist recursively. append this value.
        if N-s_list[i]>=0 and minn>(N-s_list[i]):
            minn=(min(minn, minSubsetDifference_Memoize(N-s_list[i], s_list[i+1:])))
            opts.append(minn)
    #record and memoize ultimate solution
    val=min(opts)
    T[N][k-1]=val
    
    return T[N][k-1]

#This is a helper recursive function to recreate the optimal solution.
def recreate(n, a):
    #res will store all subsets that sum to n.
    res = []
    #define find function within recreate in order to work recursively. 
    def find(a, n, solution=()):
        #if arr is empty, just return 
        if len(a)==0:
            return
        #if the first value= target, then append this value onto the solution.
        if a[0] == n:
            res.append(solution + (a[0],))
        #recursively try the rest of the sublist, saving result.
        else:
            #subtract the first value from N, save it, and consider rest of sublist
            find(a[1:], n - a[0], solution + (a[0],))
            #do not subtract first value from N, don't save it, and consider rest of sublist.
            find(a[1:], n, solution)
    #call find here
    find(a, n)
    return res
            
def minSubsetDifference(n, a):
    #find min subset sum difference by calling memoized function.
    x=minSubsetDifference_Memoize(n, a)
    #if 0 isn't the smallest min subset difference, try with n-1
    if x!=0:
        L=recreate(n-1, a)
    else:
        L=recreate(n, a)
    return (x, L[0])

In [35]:
# Code for testing your solution
# DO NOT EDIT
print(minSubsetDifference(15, [1, 2, 3, 4, 5, 10])) # Should be 0, [5, 4, 3, 2, 1]
print(minSubsetDifference(26, [1, 2, 3, 4, 5, 10])) # should be 1, [10, 5, 4, 3, 2, 1]
print(minSubsetDifference(23, [1, 2, 3, 4, 5, 10])) # should be 0, [10, 5, 4, 3, 1]
print(minSubsetDifference(18, [1, 2, 3, 4, 5, 10])) # should be 0, [10, 4, 3, 1]
print(minSubsetDifference(9, [1, 2, 3, 4, 5, 10])) # should be 0, [4, 3, 2]
print(minSubsetDifference(457, [11, 23, 37, 48, 94, 152, 230, 312, 339, 413])) # should be 1, [339, 94, 23]
print(minSubsetDifference(512, [11, 23, 37, 48, 94, 152, 230, 312, 339, 413])) # should be 0, [312, 152, 37, 11]
print(minSubsetDifference(616, [11, 23, 37, 48, 94, 152, 230, 312, 339, 413])) # should be 1, [413, 94, 48, 37]

(0, (1, 2, 3, 4, 5))
(1, (1, 2, 3, 4, 5, 10))
(0, (1, 3, 4, 5, 10))
(0, (1, 2, 5, 10))
(0, (1, 3, 5))
(1, (23, 94, 339))
(0, (11, 37, 152, 312))
(1, (23, 37, 48, 94, 413))


## 4 (E): Greedy Solution

Suppose we use the following greedy solution to solve the problem.
  * $T = \emptyset$
  * While ( $ N \geq 0 $) 
    * Select the largest element $e$ for $S$ that is smaller than $N$
    * Remove $e$ from $S$
    * Add $e$ to $T$
    * N = N - e
  * return (N, T)
  
Using an example, show that the greedy algorithm does not necessarily produce the optimal solution.

### Answer (4 lines)

An example with N=512, and a set of  [11, 23, 37, 48, 94, 152, 230, 312, 339, 413] demonstrates why the greedy algorithm isn't always optimal.   
First, 413 is selected, so that N=99 and T=[413].  
Next, 94 is the largest element that is smaller than 99, so N=5 and T=[413, 94].
There are no other numbers smaller than 5 to be selected, so that 5 is returned as the min subset sum. 

Using dynamic programming, the optimal solution is 0, [312, 152, 37, 11], which is much better.   

## Testing your solutions -- Do not edit code beyond this point